# Generated by Django 3.2.16 on 2022-10-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecalho', models.CharField(max_length=275)),
                ('paragrafo_um', models.CharField(max_length=500)),
                ('paragrafo_dois', models.CharField(max_length=500)),
                ('rodape', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250)),
                ('telefone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Oficio',
                'verbose_name_plural': 'Oficios',
            },
        ),
    ]
